#!/bin/bash
set -eu

options=(
  style=round
  width=3.0
  hidpi=on
  active_color='gradient(top_left=0xff79c0ff,bottom_right=0xffff7b72)'
  inactive_color=0x00000000
  background_color=0x00000000
  blacklist='HackermacLauncher,System Settings,Login Window,Notification Center,Control Center'
)

/opt/homebrew/bin/borders "${options[@]}"
